line_length: 150

excluded:
  - vendor
  - BuildTools

disabled_rules:
  - trailing_whitespace
  - todo # replaced by custom
  - vertical_parameter_alignment # all kinds of problems with this rule with false positives - multiple github issues
  - redundant_string_enum_value
  - nesting

identifier_name:
  excluded:
    - i
  min_length: 2
  max_length: 50
type_name:
  excluded:
    - T
  max_length: 60
type_body_length: 400
file_length: 500
function_parameter_count: 8

opt_in_rules:
  - implicit_return
  - private_outlet
  - private_action
  - force_unwrapping
implicit_return:
  included:
    - closure
    - function
    - getter