disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation

included:
  - Sources
  - Tests

excluded:
  - .build
  - Carthage
  - DerivedData
  - Pods

analyzer_rules:
  - unused_declaration
  - unused_import

force_cast: warning
force_try: warning
function_parameter_count: 
  warning: 8
  error: 10

type_name:
  min_length: 3
  max_length: 
    warning: 50
    error: 60
  excluded:
    - ID
    - URL
    - URI

identifier_name:
  min_length: 
    warning: 2
    error: 1
  max_length: 
    warning: 40
    error: 60
  excluded:
    - id
    - URL
    - x
    - y
    - i
    - j
    - pk
    - to
    - vm
    - on

vertical_whitespace:
  max_empty_lines: 2

reporter: "xcode"
