name: Swift Lint and Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Added manual trigger capability

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: SwiftLint
      run: |
        swiftlint --strict ./Sources ./Tests

  test:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2.3.0
        with:
          swift-version: "6.1"
          
      - name: Build and Test
        run: |
          swift test